name: Unit test with GitHub Actions

on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: postgres:latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run server
      run: python server.py
      env:
        POSGRES_HOST : "postgres"
        POSTGRES_PORT : 5432

    - name: Run tests
      run: |
        python -m unittest test_server.py
